namespace api_codegen.Generators;

/// <summary>生成される全C#ファイルの先頭に付与するDO NOT EDITコメント。</summary>
public static class GeneratedFileHeader
{
    public const string Text =
        """
        // <auto-generated/>
        // DO NOT EDIT: このファイルは api-codegen によって自動生成されています。
        // 直接編集せず、入力元のOpenAPI仕様書(サーバー側のhandler定義)を変更してください。

        """;
}
